### ISSUE TITLE
Rules run twice

### ISSUE THREAD

**Issue by ggasser** [mithunsatheesh/node-rules#34]
Hi,

First of all, great module.
I found that the rules are being applied twice, generating duplication in same cases. 

Version: 3.0.2

``` coffeescript
RuleEngine = require('node-rules')

rules = [
  {
      "name": "rule1",
      "condition": (R) ->
        R.when(this.value1 > 5)
      ,
      "consequence": (R) ->
        @result = false;
        @errors = @errors || []
        @errors.push('must be less than 5')
        R.next()
  }
]

fact = {
    "value1": 6
}

R = new RuleEngine(rules)

R.execute(fact, (result) ->
  console.log(JSON.stringify(result))
)
```

It should print 

```
{"value1":6,"result":false,"errors":["must be less than 5"]}
```

but instead is printing:

```
{"value1":6,"result":false,"errors":["must be less than 5","must be less than 5"]}
```

Cheers.

**Comment by mithunsatheesh** [comment]
Hi @ggasser ,

If you are looking for quick fix for this scenario, it could be fixed by switching the `R.next()` call by `R.stop()` call, as we should stop processing as this was the last rule.

The reason for the rule getting executed again on the fact seems that as we have altered the fact, rule engine has a restart process to check if the fact could have been matched by earlier rules with the new change. I will ivestigate more into this and will give you a clearer picture.

Thanks,
Mithun Satheesh

**Comment by ggasser** [comment]
Hi Mithun, thanks for the answer.

We can't use the R.stop() method since we have more than 1 rule that have to be applied at once. The previews code was just a test case to show the bug.

Thanks,

**Comment by jcorry** [comment]
I'm having a similar issue and could use some help.

I want to make changes to an element in the fact object as sequential rules execute and evaluate to true, such that at the end of execution I have a final object.

**Comment by aarosil** [comment]
+1 I am having the same issue.  In fact rules keeps running infinitely.  I am trying to build up a string result based on several different rules and concatenating to a if a condition is met.

**Comment by aarosil** [comment]
@mithunsatheesh what you think of `execute` taking `options` param where we can set `ignoreFactChange= true` (and add check for that one line 72)?  I made this change locally and it seems to work well.

**Comment by mithunsatheesh** [comment]
Hi Aaron,

The reason for this issue is when rules continue appending results on to a key in the fact object. So every time the rule engine will see that fact has changed and it needs to run the existing rules one more time over them. The fix wont be completely setting ignoreFactChange = true, But we could add a result key or user can mention a key on which the changes wont be considered by rule engine while comparing the fact changes.

If you have a fix under it, I would suggest you to add it and give us a pull request. Else I will incorporate this chages by end of this month.

**Comment by aarosil** [comment]
Hi @mithunsatheesh , I'm a bit confused about auto restart on fact change.  Since you have `restart()` in API, and presumably you'd know fact has changed in the consequence by your own code, you can restart yourself.  Or, is this more for fact changing from outside code during rule processing?

I am working on some fix and I would submit it.  Also, I would like to use promises in API so that we can have async checking of condition as well as processing consequence, what do you think?  Use case would be for example checking user permission in db to decide `condition` or retrieving a value to set as `result`

**Comment by mithunsatheesh** [comment]
Idea was to validate the fact with the already applied rules, to check if any of them matches now as the fact has changed. We can think of removing it in a later version if the user manually enforcing a restart from consequence seems a better way.
