### ISSUE TITLE
Rules Editor

### ISSUE THREAD

**Issue by bharanidharan-k** [mithunsatheesh/node-rules#50]
While the node-rules module solves the runtime problem of executing rule, how about having simple minimalist UI to author business rules? I understand its a big move, but collaboratively we can achieve.

something like, 
1. UI to author business rules based on vocabulary, 
2. decistion table to author symmetric rules, 
3. decision tree to author  asymmetric rules...

**Comment by mathcoll** [comment]
I just have began some UI implementation ; not yet mergeable.
Using this library: jQuery-QueryBuilder https://github.com/mistic100/jQuery-QueryBuilder

**Comment by bharanidharan-k** [comment]
I'm ready to contribute. You can share the branch details so we can work together

**Comment by tahaziadeh** [comment]
@mathcoll , @bharanidharan-k  any progress in your direction ?

**Comment by mathcoll** [comment]
Unfortunately I'm still blocked integrating jQuery-QueryBuilder with node-rule; mostly because of:
1. `consequence` and `condition` in node-rule are using "function(){}" in format which is not easy to handle
2. jQuery-QueryBuilder output format is using SQL syntax (or Mango), but node-rule is using javascript syntax

I was busy on other topic, but I plan to work again and maybe to find a solution for this integration. I'll let you know.

Any idea is welcome. :-)

**Comment by mithunsatheesh** [comment]
While this is a nice idea, we do not have plans to vend a UI editor as part of this package. This package will continue to provide only the absolute minimum code for the rule engine. Closing as wont fix.
